### PR TITLE
Remove _now from testing example

### PR DESCRIPTION
**Pull request by swanny85**
The `find` method looks to see if there is an `id` or `ids` present and calls the proper `find_one` or `find_many` method.

### CODE REVIEW

**Comment by swanny85** [comment]
Also added an example to find multiple ids.

**Comment by cdmwebs** [comment]
@swanny85 looks like this broke some tests. Can you update?

**Comment by swanny85** [comment]
> @swanny85 looks like this broke some tests. Can you update?

Definitely will. Odd it broke tests updating the readme. Haha.

**Comment by stefanvermaas** [comment]
You can rebase this after #26 is merged. Seems something was outdated. Addressed it in the other PR.

**Comment by stefanvermaas** [comment]
I've rebased the branch on the current master and resolved the merge issues. I think it's good to merge.

**Review by stefanvermaas — APPROVED** [review]

**Pull request merged**
